Initial Skeleton
OA-PASS/pass-policy-service pull request #21
Opened 2022-10-31 12:27 UTC by DeeMac98

Added main skeleton layout of classes, servlets and interfaces required. 
Some new classes may be added to represent multi-return values used in some of the Go functions.
Updated pom.xml with servlet dependency.
No use cases fulfilled yet. Once some Go specific syntax is converted to Java, I will be able to add functionality to the skeleton.

2022-10-31 19:33 UTC, markpatton requested changes
The Java package structure should start with org.eclipse.pass.policy

Update the README for the Java project it doesn't have to be complete, but make it accurate for the proposed design. That design should include the HTTP request and responses as well as status codes, headers, and parameters.

InternalPassClient and related clases are not needed. You will be using the existing Java PASS client. lesshttps://github.com/eclipse-pass/pass-doi-service/blob/main/src/main/java/org/dataconservancy/pass/doi/service/PassDoiServlet.java for an example of how to use it.

There are a bunch of Servlets defined to handle the endpoints /BaseURIs, /Client, /PolicyEndpoint, /PolicyService, and /RepositoriesEndpoint. It's not clear to me what all of those are doing. The README should explain what each endpoint does. I would think about having a higher level service handle the business logic and have the servlets manage the web request and dispatch it to the service.

2022-11-07 13:48 UTC, markpatton requested changes
This is getting closer. Take a look at the comments and see if you have questions.

2022-11-07 13:48 UTC, markpatton commented on .github/workflows/ci.yml
> +name: pass-policy-service Continuous Integration
This sets up Go and tries to use it to run tests. Take a look at a Java repository like pass-doi-service and copy the ci.yml from there.

2022-11-07 13:48 UTC, markpatton commented on src/main/java/org/eclipse/pass/policy/services/README.md
> +# Web API
Put this in the README.md at the root of the repository. It should not live in a src directory.

2022-11-07 13:48 UTC, markpatton commented on src/main/java/org/eclipse/pass/policy/interfaces/BaseURIReplacer.java
> +public interface BaseURIReplacer {
Is there a need to do this sort of replacement if you are using PassClient?

2022-11-07 13:48 UTC, markpatton commented on src/main/java/org/eclipse/pass/policy/rules/README.md
> +# Policy rules DSL
I would not have this in a src directory. You could have a separate directory for documentation like doc/

2022-11-07 13:48 UTC, markpatton commented on src/main/java/org/eclipse/pass/policy/services/PolicyEndpoint.java
> +@WebServlet("/PolicyEndpoint")
Use the same endpoint as before, /policies.

2022-11-07 13:48 UTC, markpatton commented on src/main/java/org/eclipse/pass/policy/services/PolicyEndpoint.java
> +public class PolicyEndpoint extends HttpServlet {
Call this PolicyServlet

2022-11-07 13:48 UTC, markpatton commented on src/main/java/org/eclipse/pass/policy/services/RepositoriesEndpoint.java
> +@WebServlet("/RepositoriesEndpoint")
Use the same endpointname as before /repositories. Also I'd change the name to RepositoriesServlet.

2022-11-07 13:48 UTC, markpatton commented on src/main/webapp/WEB-INF/web.xml
> +<!DOCTYPE web-app PUBLIC
Actually should not be needed with newer application containers, the annotations should be enough. But no harm in having.

2022-11-07 13:48 UTC, markpatton commented on src/main/webapp/index.jsp
> +<!DOCTYPE html>
Should not have this. This won't be doing anything else besides answering the endpoints.

2022-11-10 22:51 UTC, DeeMac98 commented
Updated issue: https://github.com/eclipse-pass/main/issues/340

2022-11-11 16:11 UTC, markpatton approved these changes

2022-11-11 16:13 UTC, markpatton commented
Looks good!

2022-11-11 16:13 UTC, merged